<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

<!-- links -->
    <xacro:macro name="arm_link" params="postfix">
        <link name="arm_${postfix}_link">
            <visual>
                <geometry>
                    <cylinder radius="0.03" length="0.25"/>
                </geometry>
                <origin xyz="0 0 0.125" rpy="0 0 0"/>
                <material name="gray"/>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="0.03" length="0.25"/>
                </geometry>
                <origin xyz="0 0 0.125" rpy="0 0 0"/>
            </collision>
            <xacro:cylinder_inertia m="0.3" r="0.03" h="0.25"
                                    o_xyz="0 0 0.125" o_rpy="0 0 0"/>
        </link>
    </xacro:macro>

    <xacro:arm_link postfix="1"/>
    <xacro:arm_link postfix="2"/>

    <link name= "elbow_link">
        <visual>
            <geometry>
                <box size= "0.07 0.07 0.07"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="gray"/>
        </visual>
        <collision>
            <geometry>
                <box size= "0.07 0.07 0.07"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </collision>
        <xacro:box_inertia m="0.1" x="0.07" y="0.07" z="0.07"
                           o_xyz="0 0 0" o_rpy="0 0 0"/>
    </link>

    <link name="arm_base_link">
        <visual>
            <geometry>
                <box size= "0.1 0.1 0.1"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <box size= "0.1 0.1 0.1"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </collision>
        <xacro:box_inertia m="7.0" x="0.1" y="0.1" z="0.1"
                           o_xyz="0 0 0" o_rpy="0 0 0"/>
    </link>
    
    <!-- link CAD mesh
        <visual>
            <geometry>
                <mesh filename="package://package_name/path/to/file/*.stl" scale="x y z"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="blue"/>
        </visual>-->

<!-- joints -->

    <joint name="shoulder_joint" type="revolute">
        <parent link="arm_base_link"/>
        <child link="arm_1_link"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <limit effort="100" lower="-1.0472" upper="1.0472" velocity="100"/>
        <dynamics damping="0.5" friction="0.5"/>
    </joint>

    <joint name="elbow_forearm_joint" type="revolute">
        <parent link="elbow_link"/>
        <child link="arm_2_link"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <limit effort="100" lower="-2.0944" upper="2.0944" velocity="100"/>
        <dynamics damping="0.3" friction="0.3"/>
    </joint>

    <joint name="elbow_arm_joint" type="fixed">
        <parent link="arm_1_link"/>
        <child link="elbow_link"/>
        <origin xyz="0 0 0.285" rpy="0 0 0"/>  <!--box side/2 + arm length =0.285 -->
    </joint>

    <joint name="arm_base_joint" type="prismatic">
        <parent link="base_link"/>     <!-- base_link is in the mobile base -->
        <child link="arm_base_link"/>
        <origin xyz="0 0 ${base_height}" rpy="0 0 0"/>
        <axis xyz="1 0 0"/>
        <limit effort="100" lower="${-base_length / 2.0}" upper="${base_length / 2.0}" velocity="100"/>
        <dynamics damping="0.3" friction="0.3"/>
    </joint>

</robot>