<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="cam_length" value="0.01"/>
    <xacro:property name="cam_width" value="0.1"/>
    <xacro:property name="cam_height" value="0.05"/>

    <link name="camera_link">
        <visual>
            <geometry>
                <box size="${cam_length} ${cam_width} ${cam_height}"/>
            </geometry>
            <material name="gray"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </visual>
        <collision>
            <geometry>
                <box size="${cam_length} ${cam_width} ${cam_height}"/>
            </geometry>
        </collision>
        <xacro:box_inertia m="0.1" x="${cam_length}" y="${cam_width}" z="${cam_height}" o_xyz="0 0 0" o_rpy="0 0 0"/>
    </link>
    
    <link name="camera_link_optical">
    </link>
    
    <joint name="camera_joint" type="fixed">
        <parent link="base_link"/>
        <child link="camera_link"/>
        <origin xyz="${(base_length + cam_length + 0.01) / 2.0} 0 ${base_height / 2.0}" rpy="0 0 0"/>
    </joint>

    <joint name="camera_optical_joint" type="fixed">
        <parent link="camera_link"/>
        <child link="camera_link_optical"/>
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
    </joint>

    <gazebo reference="camera_link">
        <sensor name="camera" type="camera">
            <camera>
                <horizontal_fov>1.3962634</horizontal_fov>
                <image>
                    <width>640</width>
                    <height>480</height>
                    <format>R8G8B8</format>
                </image>
                <clip>
                    <near>0.1</near>
                    <far>100</far>
                </clip>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.007</stddev>
                </noise>
                <optical_frame_id>camera_link_optical</optical_frame_id>
                <camera_info_topic>camera/camera_info</camera_info_topic>
            </camera>
            <always_on>1</always_on>
            <update_rate>30</update_rate>
            <visualize>true</visualize>
            <topic>camera/image_raw</topic>
        </sensor>
    </gazebo>

</robot>