<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- materials -->

    <material name="gray">
        <color rgba="0.5 0.5 0.5 1"/>
    </material>

    <material name="blue">
        <color rgba="0 0 1 1"/>
    </material>

    <material name="pink">
        <color rgba="1 0 1 1"/>
    </material>

    <!-- inertia tensors -->

    <xacro:macro name="box_inertia" params="m x y z o_xyz o_rpy"> <!-- o = origin -->
        <inertial>
            <mass value="${m}"/>
            <origin xyz="${o_xyz}" rpy="${o_rpy}"/>
            <inertia ixx="${(m/12) * (y*y + z*z)}" ixy="0" ixz="0" 
                     iyy="${(m/12) * (x*x + z*z)}" iyz="0" 
                     izz="${(m/12) * (x*x + y*y)}"/> <!-- inertia matrix -->
        </inertial>
    </xacro:macro>

    <xacro:macro name="cylinder_inertia" params="m r h o_xyz o_rpy">
        <inertial> 
            <mass value="${m}"/>
            <origin xyz="${o_xyz}" rpy="${o_rpy}"/>
            <inertia ixx="${(m/12) * (3*r*r + h*h)}" ixy="0" ixz="0" 
                     iyy="${(m/12) * (3*r*r + h*h)}" iyz="0" 
                     izz="${(m/2) * (r*r)}"/> <!-- inertia matrix -->
            <origin xyz="${(base_length / 2.0) - (wheel_length / 2.0)} ${base_width / 2.0} ${base_height / 2.0}" rpy="0 0 0"/>
            <axis xyz="0 1 0"/>
        </inertial>
    </xacro:macro>

    <xacro:macro name="sphere_inertia" params="m r o_xyz o_rpy">
        <inertial>
            <mass value="${m}"/>
            <origin xyz="${o_xyz}" rpy="${o_rpy}"/>
            <inertia ixx="${(2/5) * m * r * r}" ixy="0" ixz="0" 
                     iyy="${(2/5) * m * r * r}" iyz="0" 
                     izz="${(2/5) * m * r * r}"/> <!-- inertia matrix -->
        </inertial>
    </xacro:macro>

</robot>